"""Refined relationships in models

Revision ID: 15a4742a24da
Revises: bfda986b307d
Create Date: 2024-12-25 15:21:55.230408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a4742a24da'
down_revision = 'bfda986b307d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
