"""Refined relationships in models

Revision ID: 3bc2567e506a
Revises: a8952c4bdf70
Create Date: 2024-12-25 16:56:12.538183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc2567e506a'
down_revision = 'a8952c4bdf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
