"""Refined relationships in models

Revision ID: 3e79c243db08
Revises: 15a4742a24da
Create Date: 2024-12-25 15:25:21.978574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e79c243db08'
down_revision = '15a4742a24da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
