"""Refined relationships in models

Revision ID: 454923c07784
Revises: 3e79c243db08
Create Date: 2024-12-25 15:28:31.722786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454923c07784'
down_revision = '3e79c243db08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
