"""Refined relationships in models

Revision ID: 4d75810b6b75
Revises: cb9a7ed8af4b
Create Date: 2024-12-25 15:56:57.766299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d75810b6b75'
down_revision = 'cb9a7ed8af4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
