"""Refined relationships in models

Revision ID: 52cb68449881
Revises: c588817e520b
Create Date: 2024-12-25 15:32:20.766425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cb68449881'
down_revision = 'c588817e520b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
