"""Refined relationships in models

Revision ID: a8952c4bdf70
Revises: 4d75810b6b75
Create Date: 2024-12-25 16:00:15.876105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8952c4bdf70'
down_revision = '4d75810b6b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
