"""empty message

Revision ID: bfda986b307d
Revises: 1330f5a3041d
Create Date: 2024-12-25 13:21:10.263154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfda986b307d'
down_revision = '1330f5a3041d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'filename',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('comment', 'timestamp')
    op.add_column('task', sa.Column('name', sa.String(length=255), nullable=True))
    op.execute('UPDATE task SET name = \'default_name\' WHERE name IS NULL')
    op.alter_column('task', 'name', nullable=False)
    op.alter_column('task', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('task', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('task', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('task', 'name')
    op.add_column('comment', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('attachment', 'filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
