"""Refined relationships in models

Revision ID: c588817e520b
Revises: 454923c07784
Create Date: 2024-12-25 15:30:52.719071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c588817e520b'
down_revision = '454923c07784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
