"""Refined relationships in models

Revision ID: cb9a7ed8af4b
Revises: ef9adbd4b788
Create Date: 2024-12-25 15:50:33.339902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9a7ed8af4b'
down_revision = 'ef9adbd4b788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
