"""Refined relationships in models

Revision ID: e02af5d6262a
Revises: 52cb68449881
Create Date: 2024-12-25 15:34:52.916714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02af5d6262a'
down_revision = '52cb68449881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
