"""Fixed relationship conflicts

Revision ID: ef9adbd4b788
Revises: f37bc35472c0
Create Date: 2024-12-25 15:49:08.727133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9adbd4b788'
down_revision = 'f37bc35472c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
