"""Refined relationships in models

Revision ID: f37bc35472c0
Revises: e02af5d6262a
Create Date: 2024-12-25 15:37:16.061359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37bc35472c0'
down_revision = 'e02af5d6262a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
