"""add email to user

Revision ID: xxxx_add_email_to_user
Revises: d97485b7f51c
Create Date: 2024-12-24 16:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'xxxx_add_email_to_user'
down_revision = 'd97485b7f51c'
branch_labels = None
depends_on = None


def upgrade():
    # Add the email column without the unique constraint
    op.add_column('user', sa.Column('email', sa.String(length=150), nullable=False, server_default='default@example.com'))
    
    # Populate the email column with unique values
    op.execute("UPDATE \"user\" SET email = CONCAT('user_', id, '@example.com') WHERE email = 'default@example.com'")
    
    # Remove the default value constraint
    op.alter_column('user', 'email', server_default=None)
    
    # Add the unique constraint
    op.create_unique_constraint(None, 'user', ['email'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
